### ISSUE TITLE
Thesis

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/parataxis#10]
Hi @Flamefire , did you already publish your thesis somewhere, e.g., Zenodo.org ? [Example](https://zenodo.org/record/15924).

Cheers,
Axel

**Comment by Flamefire** [comment]
No I didn't and Can't really do that from overseas. The thesis is on the team(?) drive so if it is possible for some of you to publish that (especially in the hzdr archive) that works be great

**Comment by bussmann** [comment]
Hey! Stay afkb and have fun with the Kiwis ;-)
Best wishes, Michael

**Comment by ax3l** [comment]
@Flamefire happy new year!

The publishing on Zenodo, if you like to, would be something you have to do personally when returning due to copyright reasons in case you want to assign a creative commons license (we can assist you with that). That long, we can put it on the hompage, too.

Regarding your HZDR copy, I can't find the final PDF on the team drive but @HighIander hand one in his inbox and there is a DVD swirling around with it. Can you please send us your defense slides, too?

I just found your 300 GB raw data in `production/grund_diplom` that I now copied to the tape archives (archive ID: 2388).

**Comment by Flamefire** [comment]
The work was published at zenodo under CC-BY-SA with the DOI 10.5281/zenodo.1164654 
[![DOI 10.5281/zenodo.1164654](https://user-images.githubusercontent.com/309017/35735850-625e6f26-0826-11e8-9ee7-83a87b4da787.png)](https://dx.doi.org/10.5281/zenodo.1164654)

The defense slides and another copy were sent to the HZDR.

Thank you for the help!
