### ISSUE TITLE
Runtime tests fail because wrong HDF5 module is chosen

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/parataxis#12]
To execute a runtime test I did the following:

`export TBG_SUBMIT=qsub`   
`export TBG_TPLFILE=$HOME/build_parataxis/submit/hypnos-hzdr/k20_profile.tpl`   

in $HOME/parataxis:
`python buildSystem/runTests.py -e examples/DoubleSlit -o /bigdata/hplsim/scratch/garten70/ParaTAXIS/001_runTest`

ParaTAXIS is being built with the following modules:

1) mpfr/3.1.2
2) mpc/1.0.1
3) gmp/5.1.1
4) gcc/4.8.2
5) cmake/3.3.0
6) cuda/7.5
7) openmpi/1.8.4.kepler.cuda75
8) hdf5-parallel/1.8.14
9) libmxml/2.8
10) adios/1.10.0
11) python/3.4.3
12) editor/gedit/2.26.1
13) qt/4.8.2
14) boost/1.60.0

and a slightly changed version of libsplash/1.4.0

After executing the command `python buildSystem/runTests.py ...` everything compiles, jobs get submitted but they all fail. From 001_runTest/output/DoubleSlit_256CellsConstPos/stderr one can see:

	This module will set up environment variables for gcc/4.9.2.

	This module will set up environment variables for cmake/3.7.2.

	This module will set up environment variables for cuda/8.0.

	This module will set up environment variables
	for the Message-Passing Interface environment openmpi/1.8.6.kepler.cuda80.
	USE THIS MPI VERSION ON KEPLER NODES ONLY!!!!

	This module will set up environment variables for boost/1.60.0.

	This module will set up environment variables for pngwriter/0.5.6.

	This module will set up environment variables for hdf5-parallel/1.8.15.

	This module will set up environment variables for libsplash/1.6.0.

	This module will set up environment variables for numactl/2.0.7.

	This module will set up environment variables for paraview/3.98.laser.

	This module will set up environment variables for apr/1.5.1

	This module will set up environment variables for apr-util/1.5.3

	This module will set up environment variables for serf/1.3.6.

	This module will set up environment variables for svn/1.8.8 .

	This module will set up environment variables for gnuplot/4.2.6.

[1,0]<stderr>:/bigdata/hplsim/scratch/garten70/ParaTAXIS/001_runTest/output/DoubleSlit_256CellsConstPos/bin/XRayTracing: error while loading shared libraries: libhdf5.so.9: cannot open shared object file: No such file or directory
[1,1]<stderr>:/bigdata/hplsim/scratch/garten70/ParaTAXIS/001_runTest/output/DoubleSlit_256CellsConstPos/bin/XRayTracing: error while loading shared libraries: libhdf5.so.9: cannot open shared object file: No such file or directory
[1,2]<stderr>:/bigdata/hplsim/scratch/garten70/ParaTAXIS/001_runTest/output/DoubleSlit_256CellsConstPos/bin/XRayTracing: error while loading shared libraries: libhdf5.so.9: cannot open shared object file: No such file or directory

**Comment by n01r** [comment]
That up there is exactly my current list of modules from my `picongpu.profile`.

**Comment by ax3l** [comment]
but you are loading libSplash in `picongpu.profile` again as a module, which might not be ideal.
Make sure the `.tpl` file also sources the right profile.

**Comment by n01r** [comment]
Yes that was the problem - I will add a `parataxis.profile.example` to `parataxis/submit/hypnos-hzdr/` and have the `.tpl` files source `parataxis.profile`.

**Comment by n01r** [comment]
Moved this to #14
